services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pubmessagesapp
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - DATABASE_PASSWORD=Very0#ArrrdT0gue$sPAS$worD531
    ports:
      - "433:433"
    volumes:
      - ./dataprotection-keys:/app/dataprotection-keys
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443" 
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge